### ISSUE TITLE
Gather game assets

### ISSUE THREAD

**Issue by tripathi-gaurav** [tripathi-gaurav/teen-patti#2]
Gather assets required for the game

**Comment by saurabhbothra** [comment]
Done.

**Comment by tripathi-gaurav** [comment]
Not done yet.

**Comment by tripathi-gaurav** [comment]
Complete with this [commit](https://github.com/tripathi-gaurav/teen-patti/commit/6d0c5817ec7dabc2060a49ac12f1f1e2ff9966ad)
